### ISSUE TITLE
060 device support?

### ISSUE THREAD

**Issue by AndyBlake** [cnvogelg/plipbox#12]
Hiya
Which device should I use if I have an 060 CPU? Does plipbox support that cpu?
Kind regards
Andy

**Comment by salocinx** [comment]
You can use the 040 device for the 060 CPU. Works fine in my A4000/060.

**Comment by AndyBlake** [comment]
Thanks, I'll try that out

**Comment by patrikaxelsson** [comment]
@AndyBlake: please close the issue if you have no remaining problems with this
