### ISSUE TITLE
Plipbox does not work with new Arduino Nano Clones

### ISSUE THREAD

**Issue by salocinx** [cnvogelg/plipbox#15]
Hi. I recently have ordered some Arduino Nano V3 clones, those which are shipped with the new bootloader. The Plipbox does not work with them. It works with the ones that are shipped with the old bootloader. Any experience or idea why not? Thanks!

**Comment by patrikaxelsson** [comment]
Does plipbox work if you reprogram them with the old bootloader?

Btw, can you please be very specific what is the old and new bootloader?

**Comment by salocinx** [comment]
No, they never worked... Simply bad chips... It does not depend old/new bootlloader, just get some quality Arduino Nano from a serious supplier. I now use those from Joy-It, cost around 10+ USD, but they work at least without problems.

**Comment by patrikaxelsson** [comment]
Cheers, great to hear and good info!

**Comment by patrikaxelsson** [comment]
I guess this issue can be closed as you found the problem?

**Comment by salocinx** [comment]
Yes 👍🏽 It's closed.
