### ISSUE TITLE
Possible Bug in server.c?

### ISSUE THREAD

**Issue by MHeinrichs** [cnvogelg/plipbox#9]
in the amiga driver server.c Im couious about line 391:
The way the for-loop terminates, it doesn't traverse the list until the last element but till the 2nd last. 
Is that OK?

**Comment by cnvogelg** [comment]
It looks strange but its correct. This is the right way to iterate an Exec list. These data structures have a "virtual" node (in the list structure itself) at the head and tail of each list. Therefore you have to stop iterating through the data nodes at the 2nd last one.
See e.g. [Exec Lists and Queues](http://wiki.amigaos.net/wiki/Exec_Lists_and_Queues) for details.
